services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: filamentfour_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - mailhog
        ports:
            - "9000:9000"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: filamentfour_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        platform: linux/amd64  # Important for Apple Silicon
        container_name: filamentfour_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3308:3306"  # use 3308 on host to avoid conflict
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf  # Optional: custom MySQL config
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog
        platform: linux/amd64  # Explicit platform for Apple Silicon compatibility
        ports:
            - "8025:8025"   # Web UI
            - "1025:1025"   # SMTP server
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
